### ISSUE TITLE
Make on screen buttons use entities

### ISSUE THREAD

**Issue by AlexBezuska** [SplatJS/splat-ecs#28]

**Comment by ericlathrop** [comment]
The input system allows you to specify a rectangle on screen that will act as a button. The problem is that the rectangle is fixed, and there's no way to alter it in the game. It would be better if an entity with a position/size could act as a button, that way you could move it around, center it, etc.

Actually, the input system probably needs a way to add virtual buttons and axes where the state can be set at runtime from any code. This would be really flexible, and allow for an on-screen joystick as well as buttons.
